
#KEEP SYNC WITH src/constants.h

CCT_MODULE_PREFIX = "CCT:"
CCT_MODULE_KEY_2_CLIENT  = CCT_MODULE_PREFIX + "K2C:"
CCT_MODULE_QUERY_2_CLIENT = CCT_MODULE_PREFIX + "Q2C:"
CCT_MODULE_CLIENT_2_QUERY = CCT_MODULE_PREFIX + "C2Q:"
CCT_MODULE_KEY_2_QUERY  = CCT_MODULE_PREFIX + "K2Q:"
CCT_MODULE_QUERY_2_KEY  = CCT_MODULE_PREFIX + "Q2K:"
CCT_MODULE_QUERY_CLIENT =  CCT_MODULE_PREFIX + "QC:" 
CCT_MODULE_KEY_SEPERATOR =  ":" 


CCT_TTL = 10  # This must be same as CCT_TTL in constants.h
CCT_EXPIRE_HALF_TIME = ( CCT_TTL / 2 ) + 1