
#KEEP SYNC WITH src/constants.h

CCT_MODULE_PREFIX = "CCT:"
CCT_MODULE_KEY_2_CLIENT  = CCT_MODULE_PREFIX + "TRACKED_KEYS:"
CCT_MODULE_QUERY_2_CLIENT = CCT_MODULE_PREFIX + "TRACKED_QUERIES:"
CCT_MODULE_QUERY_CLIENT =  CCT_MODULE_PREFIX + "TRACKED_CLIENT_QUERIES:" ;
CCT_TTL = 10 