#ifndef CONSTANTS_H
#define CONSTANTS_H

#define CCT_MODULE_PREFIX "CCT:"
#define CCT_MODULE_TRACKING_PREFIX CCT_MODULE_PREFIX "TRACKED_KEYS:"
#define CCT_MODULE_CLIENT_PREFIX CCT_MODULE_PREFIX "REGISTERED_CLIENTS:"
#define CCT_MODULE_QUERY_PREFIX CCT_MODULE_PREFIX "TRACKED_QUERIES:"
#define CCT_MODULE_KEY_SEPERATOR ":"
#define CCT_MODULE_KEY_LEVEL "."
#define CCT_MODULE_KEY_LEVEL_WITH_ESCAPE "\\."

#endif /* CONSTANTS_H */