#ifndef CONSTANTS_H
#define CONSTANTS_H

#define CCT_MODULE_PREFIX "CCT:"
#define CCT_MODULE_CLIENT_PREFIX "CCT:CLIENT:"
#define CCT_MODULE_QUERY_PREFIX "CCT:QUERY:"
#define CCT_MODULE_KEY_SEPERATOR ":"

#endif /* CONSTANTS_H */